### PR TITLE
Harmony version

### PR DESCRIPTION
**Pull request by calvin-fisher**
Updated mod to use Harmony instead of detour

### CODE REVIEW

**Comment by DingoDjango** [comment]
```
        static bool Prefix(Thing _instance, IEnumerable<Thing> _result, ref float efficiency)
        {
            if (_instance.def.IsClothes() || _instance.def.IsAdvancedArmor() || _instance.def.IsArmor())
            {
                _result = _SmeltProducts(_instance);
                return false;
            }
            else
            {
                return true;
            }
        }
```

Pretty sure this should be:

```
        static bool Prefix(Thing __instance, ref IEnumerable<Thing> __result)
        {
            if (__instance.def.IsClothes() || __instance.def.IsAdvancedArmor() || __instance.def.IsArmor())
            {
                __result = _SmeltProducts(__instance);
                return false;
            }
            return true;
        }
```

Note the double underscore (__instance, __result) + ref keyword. Did you test to see that this works?

**Comment by calvin-fisher** [comment]
Yeah, it seemed to work fine.  Pawns smelted clothing at the tailor workbench and produced an appropriate-seeming amount of materials.

**Comment by calvin-fisher** [comment]
@DingoDjango thanks for the heads-up.  I went back and double-checked, and I must not have copied over my updated .dll before testing, because this was definitely not working for a couple reasons.  You were right about the double-underscore, and I had also reversed the return value from what it should have been.  Both fixed now.

Including the `else` block for readability and omitting `ref` on the value type method parameter were intentional, though.

**Comment by DingoDjango** [comment]
Your patch does nothing to the result if you don't use ref. Right now all you're doing is stopping SmeltProducts from executing if __instance doesn't meet certain conditions. You've also used ref float efficiency but don't use that float at all.

**Pull request closed without merging**
